on:
  workflow_run:
    workflows: ["Quality Checks"]
    branches: [main]
    types:
      - completed

name: Cross Compliation

defaults:
  run:
    working-directory: macbrew-proxy

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}