# Shamelessly stolen from https://github.com/dandavison/delta/blob/master/.github/workflows/cd.yml
# Thanks dandanvison!

name: Continuous Deployment

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  BREWERS_FRIEND_API_KEY: DUMMY_KEY_FOR_TESTS

jobs:
  publish:
    name: Publish Build Artefact
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - { os: macos-latest, target: x86_64-apple-darwin, use-cross: false }
          # - {
          #     os: windows-latest,
          #     target: x86_64-pc-windows-msvc,
          #     use-cross: false,
          #   }
          - {
              os: ubuntu-latest,
              target: x86_64-unknown-linux-gnu,
              use-cross: false,
            }
          - {
              os: ubuntu-latest,
              target: i686-unknown-linux-gnu,
              use-cross: true,
            }
          - {
              os: ubuntu-latest,
              target: arm-unknown-linux-gnueabihf,
              use-cross: true,
            }

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cargo build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.7
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.job.use-cross }}
          args: --release --target ${{ matrix.job.target }}

      - name: Install required dependencies
        shell: bash
        run: |
          if [[ ${{ matrix.job.target }} == arm-unknown-linux-gnueabihf ]]; then
              sudo apt update
              sudo apt-get install -y binutils-arm-linux-gnueabihf
          fi
          if [[ ${{ matrix.job.target }} == aarch64-unknown-linux-gnu ]]; then
              sudo apt update
              sudo apt-get install -y binutils-aarch64-linux-gnu
          fi

      - name: Rename binary
        shell: bash
        run: |
          mv target/release/macbrew-proxy ./macbrew-proxy-${{ matrix.job.target }}

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macbrew-proxy-${{ matrix.job.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
